"""
MwohaOS Settings & Configuration Test Suite
Verifies timezone, environment separation, and user settings page (Sections 12, 13, 19).
"""
import pytest
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from apps.accounts.models import UserPreference


@pytest.mark.django_db
class TestSettingsAndPreferences:
    def test_timezone_default_configuration(self):
        """Verifies timezone defaults to Africa/Nairobi and USE_TZ is enabled."""
        assert settings.TIME_ZONE == "Africa/Nairobi"
        assert settings.USE_TZ is True

    def test_timezone_aware_datetimes(self):
        """Verifies datetimes generated by timezone.now() are timezone-aware."""
        now = timezone.now()
        assert timezone.is_aware(now)

    def test_environment_configuration_values(self):
        """Verifies critical environment-driven settings exist."""
        assert hasattr(settings, "DATABASES")
        assert hasattr(settings, "CELERY_BROKER_URL")
        assert hasattr(settings, "CELERY_RESULT_BACKEND")
        assert hasattr(settings, "MWOHAOS_TIMEZONE") or hasattr(settings, "TIME_ZONE")

    def test_settings_page_requires_authentication(self, client):
        """Anonymous access to /settings/ redirects to login."""
        url = reverse("accounts:settings")
        response = client.get(url)
        assert response.status_code == 302
        assert reverse("accounts:login") in response.url

    def test_settings_page_loads_for_authenticated_user(self, authenticated_client, test_user):
        """Authenticated user can view account, preferences, and system sections."""
        url = reverse("accounts:settings")
        response = authenticated_client.get(url)
        assert response.status_code == 200
        assert b"Platform Settings" in response.content
        assert b"Account" in response.content
        assert b"Preferences" in response.content
        assert b"System" in response.content
        assert test_user.username.encode() in response.content

    def test_update_preferences(self, authenticated_client, test_user):
        """User can update timezone preference."""
        url = reverse("accounts:settings")
        response = authenticated_client.post(url, {
            "action": "update_preferences",
            "timezone": "Europe/London",
            "email_notifications": True,
        })
        assert response.status_code == 302
        pref = UserPreference.objects.get(user=test_user)
        assert pref.timezone == "Europe/London"
        assert pref.email_notifications is True
